name: iquarix
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.3
  get_it: ^9.2.0
  shared_preferences: ^2.5.4
  easy_localization: ^3.0.8
  keyboard_dismisser: ^3.0.0
  adaptive_theme: ^3.7.2
  equatable: ^2.0.7
  go_router: ^17.0.1
  device_info_plus: ^12.3.0
  dio: ^5.9.0
  mask_text_input_formatter: ^2.9.0
  freezed_annotation: ^3.1.0
  pinput: ^6.0.1
  yandex_mapkit: ^4.2.1
  geolocator: ^14.0.2
  uuid: ^4.5.2
  firebase_core: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:

  uses-material-design: true


  assets:
    - assets/svg/
    - assets/png/
    - assets/animation/
    - assets/languages/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

